version: '3'

services:
  ddbb:
    image: mongo:3.6  
    ports:
      - 27017:27017
    volumes:
      - ./tmp/db:/data/db

  app:
    build:
      context: .
    image: ghcr.io/democraciaenred/bien-restituido:latest
    volumes:
      - .:/usr/src/app    
      - /usr/src/app/.next    
      - /usr/src/app/node_modules
    env_file:
      - .env.local
    depends_on:
      - ddbb
    ports:
      - 3000:3000
    command: npm run dev